### ISSUE TITLE
Valid() logic now inverted

### ISSUE THREAD

**Issue by jayd3e** [dcu/go-authy#4]
With [this change](https://github.com/dcu/go-authy/commit/18cfcf7587f90c13570219660c8bac4cf1fb4519#diff-eda27065f88a29adbe6d90f48f5006e9R83), the logic was inverted for `Valid()`.  This makes it return false on successes and true on failures.  This is going to break everyones' code.

**Comment by dcu** [comment]
sorry about that, I need to fix the unit tests. Thanks for reporting
